language: python
sudo: false
python:
 - "3.6"
 - "3.5"
 - "3.4"
env:
 - DJANGO_VERSION=1.8.17
 - DJANGO_VERSION=1.10.5
install:
 - pip install -r requirements-dev.txt
 - pip install -q Django==$DJANGO_VERSION
script:
 - python setup.py ultratest
