version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2
        environment:
          DJANGO_VERSION: 2.2.2
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements-dev.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-dev.txt
            pip install -q Django==$DJANGO_VERSION
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements-dev.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            python setup.py ultratest
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
